{% set so_number = '161' %}
{% set epoch = '1' %}
{% set version_prefix = epoch + '!' + so_number %}
{% set revision = '3030' %}
{% set version = version_prefix + '.' + revision %}
# This is revision 3030. (git rev-list HEAD | wc -l)
{% set commit = "8bd6d28025c9dcc101cb194f9141bcff3ea91500" %}

package:
  name: x264
  version: {{ version }}

source:
  # need to use the git source to make version.sh in source work
  git_url: https://code.videolan.org/videolan/x264/
  git_rev: {{ commit }}

build:
  number: 0
  run_exports:
    - x264 >={{ version }},<{{ epoch + '!' }}{{ so_number|int + 1 }}

requirements:
  build:
    - gnuconfig  # [unix]
    - {{ compiler("c") }}
    - perl
    - nasm
    - make
  host:

test:
  commands:
    - test -f ${PREFIX}/include/x264.h                     # [unix]
    - test -f ${PREFIX}/lib/libx264.a                      # [unix]
    - test -f ${PREFIX}/lib/libx264.dylib                  # [osx]
    - test -f ${PREFIX}/lib/libx264.{{ so_number }}.dylib  # [osx]
    - test -f ${PREFIX}/lib/libx264.so                     # [linux]
    - test -f ${PREFIX}/lib/libx264.so.{{ so_number }}     # [linux]
    - x264 --help                                          # [unix]

about:
  home: http://www.videolan.org/developers/x264.html
  license: GPL-2.0
  license_file: COPYING
  summary: A free software library for encoding video streams into the H.264/MPEG-4 AVC format.

extra:
  recipe-maintainers:
    - jakirkham
    - 183amir
    - carlodri
    - sdvillal
